import mongoose from "mongoose";
const {Schema} = mongoose;

const sensorSchema = new mongoose.Schema({
    id:{
        type:Number,
    },
    sensor1:{
        type:Number
    },
    sensor2:{
        type:Number
    },
    sensor3:{
        type:Number
    },
    sensor4:{
        type:Number
    },
    sensor5:{
        type:Number
    },
    sensor6:{
        type:Number
    },
    sensor7:{
        type:Number
    },
    sensor8:{
        type:Number
    },
    sensor9:{
        type:Number
    },
    sensor10:{
        type:Number
     },
    sensor11:{
        type:Number
    },
    sensor12:{
        type:Number
    },
    sensor13:{
        type:Number
    },
    sensor14:{
        type:Number
    },
    sensor15:{
        type:Number
    },
    sensor16:{
        type:Number
    },
    sensor17:{
        type:Number
    },
    sensor18:{
        type:Number
    },
    sensor19:{
        type:Number
    },
    sensor20:{
        type:Number
    },
    sensor21:{
        type:Number
    },
    sensor22:{
        type:Number
    },
    sensor23:{
        type:Number
    },
    sensor24:{
        type:Number
    },
    sensor25:{
        type:Number
    },
    sensor26:{
        type:Number
    },
    sensor27:{
        type:Number
    },
    sensor28:{
        type:Number
    },
    sensor29:{
        type:Number
    },
    sensor30:{
        type:Number
    },
    sensor31:{
        type:Number
    },
    sensor32:{
        type:Number
    },
    sensor33:{
        type:Number
    },
    sensor34:{
        type:Number
    },
    sensor35:{
        type:Number
    },
    sensor36:{
        type:Number
    },
    sensor37:{
        type:Number
    },
    sensor38:{
        type:Number
    },
    sensor39:{
        type:Number
    },
    sensor40:{
        type:Number
    },
    sensor41:{
        type:Number
    },
    sensor42:{
        type:Number
    },
    sensor43:{
        type:Number
    },
    sensor44:{
        type:Number
    },
    sensor45:{
        type:Number
    },
    sensor46:{
        type:Number
    },
    sensor47:{
        type:Number
    },
    sensor48:{
        type:Number
    },
    sensor49:{
        type:Number
    },
    sensor50:{
        type:Number
    },
    sensor51:{
        type:Number
    },
    sensor52:{
        type:Number
    },
    sensor53:{
        type:Number
    },
    sensor54:{
        type:Number
    },
    sensor55:{
        type:Number
    },
    sensor56:{
        type:Number
    },
    sensor57:{
        type:Number
    },
    sensor58:{
        type:Number
    },
    sensor59:{
        type:Number
    },
    sensor60:{
        type:Number
    },
    sensor61:{
        type:Number
    },
    sensor62:{
        type:Number
    },
    sensor63:{
        type:Number
    },
    sensor64:{
        type:Number
    },
    sensor65:{
        type:Number
    },
    sensor66:{
        type:Number
    },
    sensor67:{
        type:Number
    },
    sensor68:{
        type:Number
    },
    sensor69:{
        type:Number
    },
    sensor70:{
        type:Number
    },
    sensor71:{
        type:Number
    },
    sensor72:{
        type:Number
    },
    sensor73:{
        type:Number
    },
    sensor74:{
        type:Number
    },
    sensor75:{
        type:Number
    },
    sensor76:{
        type:Number
    },
    sensor77:{
        type:Number
    },
    sensor78:{
        type:Number
    },
    sensor79:{
        type:Number
    },
    sensor80:{
        type:Number
    },
    sensor81:{
        type:Number
    },
    sensor82:{
        type:Number
    },
    sensor83:{
        type:Number
    },
    sensor84:{
        type:Number
    },
    sensor85:{
        type:Number
    },
    sensor86:{
        type:Number
    },
    sensor87:{
        type:Number
    },
    sensor88:{
        type:Number
    },
    sensor89:{
        type:Number
    },
    sensor90:{
        type:Number
    },
    sensor91:{
        type:Number
    },
    sensor92:{
        type:Number
    },
    sensor93:{
        type:Number
    },
    sensor94:{
        type:Number
    },
    sensor95:{
        type:Number
    },
    sensor96:{
        type:Number
    },
    sensor97:{
        type:Number
    },
    sensor98:{
        type:Number
    },
    sensor99:{
        type:Number
    },
    sensor100:{
        type:Number
    },
    sensor101:{
        type:Number
    },
    sensor102:{
        type:Number
    },
    sensor103:{
        type:Number
    },
    sensor104:{
        type:Number
    },
    sensor105:{
        type:Number
    },
    sensor106:{
        type:Number
    },
    sensor107:{
        type:Number
    },
    sensor108:{
        type:Number
    }
},{timestamps: true});

export default mongoose.model('sensor',sensorSchema);